development:
  adapter: postgresql
  database: <%= ENV["PG_DB_NAME"] %>
  host: <%= ENV["PG_DB_HOST"] %>
  username: <%= ENV["PG_DB_USERNAME"] %>
  password: <%= ENV["PG_DB_PASSWORD"] %>
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <%= ENV["PG_DB_NAME"] %>
  host: <%= ENV["PG_DB_HOST"] %>
  username: <%= ENV["PG_DB_USERNAME"] %>
  password: <%= ENV["PG_DB_PASSWORD"] %>
  pool: 5
  timeout: 5000

