production:
  clients:
    default:
      database: <%= ENV['DB_NAME'] %>
      hosts:
        - <%= "#{ENV['DB_HOST']}:#{ENV['DB_PORT']}" %>
      options:
        user: '<%= ENV['DB_USER'] %>'
        password: '<%= ENV['DB_PASSWORD'] %>'

development:
  clients:
    default:
      database: <%= ENV['DB_NAME'] %>
      hosts:
          - <%= "#{ENV['DB_HOST']}:#{ENV['DB_PORT']}" %>
      options:
        user: '<%= ENV['DB_USER'] %>'
        password: '<%= ENV['DB_PASSWORD'] %>'

