# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aff025aec80b264d59c07c0b218aa5f936e84b8b7b671cfab3eb3a205ad6efd0912a7e748cb6e740b945d67303a23e0ba2d8433456a40461ad074b1256e78810

test:
  secret_key_base: a23bdb76cb235dde07f13599aba6645febd4b64fdc1855c29409e43824473d7668720bd1bbe28fbbc6b7d34e97f89416514b6a036f87974da0e2222e4ebc435f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_DEVELOPMENT"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_TEST"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_PRODUCTION"] %>
